### ISSUE TITLE
Recent SSL Change?

### ISSUE THREAD

**Issue by Narkoleptika** [flatpickr/flatpickr.github.io#1]
I'm not sure if the page was using ssl before, but it is now and it's apparently requesting assets with http. This was fine yesterday, but it's been broken for me all day today.

![screen shot 2018-02-11 at 9 49 20 pm](https://user-images.githubusercontent.com/7088166/36084816-bab24d90-0f75-11e8-8d29-4eb7fb6f5189.jpg)

**Comment by chmln** [comment]
Thanks for the notice!
Just had to re-gen the docs with the updated URL.

All good now.
